name: Build and deploy Node.js app to Azure Web App - techzickweb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Step 1: Build frontend (React + Vite)
      - name: Install and build frontend
        working-directory: ./src/client
        run: |
          npm install
          npm run build

      # Step 2: Install backend dependencies
      - name: Install backend dependencies
        working-directory: ./src
        run: npm install

      # Step 3: Copy frontend dist into backend
      - name: Copy frontend build to backend
        run: |
          rm -rf src/public
          cp -r src/client/dist src/public

      # Step 4: Zip the backend (including built frontend)
      - name: Zip backend for deployment
        run: zip -r release.zip src

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2C36BBB51D7F4A19A27DBB51C5097AB4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9EEA4D2D99D04430B6BB9A4708B5FFE7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9F56615A6DDB48C2A5D8209F3B1F79B3 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'techzickweb'
          slot-name: 'Production'
          package: ./src
